rm -f -r ../build
mkdir ..\build
cd ..\build
cmake ../ -G"Unix Makefiles" -DPROJ_CONFIG="D:/MCU/TF-M/trusted-firmware-m/configs/ConfigPsaApiTestIPCTfmLevel2.cmake" -DTARGET_PLATFORM=M2351 -DCOMPILER=ARMCLANG -DCMAKE_BUILD_TYPE=RELEASE -DITS_RAM_FS=OFF -DBL2=False -DMBEDTLS_DEBUG=OFF -DPSA_API_TEST_SECURE_STORAGE=OFF -DPSA_API_TEST_CRYPTO=OFF -DPSA_API_TEST_ATTESTATION=ON -DBUILD_PLAT_TEST=False -DITS_CREATE_FLASH_LAYOUT=1
@REM cmake ../ -G"Unix Makefiles" -DPROJ_CONFIG="D:/MCU/TF-M/trusted-firmware-m/configs/ConfigRegressionIPCTfmLevel2.cmake" -DTARGET_PLATFORM=M2351 -DCOMPILER=ARMCLANG -DCMAKE_BUILD_TYPE=RELEASE -DITS_RAM_FS=OFF -DBL2=False -DBUILD_PLAT_TEST=False -DBUILD_DWARF_VERSION=2 -DMBEDTLS_DEBUG=OFF -DITS_CREATE_FLASH_LAYOUT=1
make
