rm -f -r ../build
mkdir ..\build
cd ..\build
cmake ../ -G"Unix Makefiles" -DPROJ_CONFIG="D:/MCU/TF-M/trusted-firmware-m/configs/ConfigPsaApiTestIPCTfmLevel2.cmake" -DTARGET_PLATFORM=M2351 -DCOMPILER=ARMCLANG -DCMAKE_BUILD_TYPE=RELEASE -DMBEDTLS_DEBUG=OFF -DPSA_API_TEST_INTERNAL_TRUSTED_STORAGE=ON -DPSA_API_TEST_SECURE_STORAGE=OFF -DPSA_API_TEST_CRYPTO=OFF -DBL2=False -DBUILD_PLAT_TEST=False -DBUILD_DWARF_VERSION=2 
make
