rm -f -r ../build
mkdir ..\build
cd ..\build
cmake ../ -G"Unix Makefiles" -DPROJ_CONFIG="D:/MCU/TF-M/trusted-firmware-m/configs/ConfigPsaApiTest.cmake" -DTARGET_PLATFORM=M2351 -DCOMPILER=ARMCLANG -DCMAKE_BUILD_TYPE=DEBUG -DITS_RAM_FS=OFF  -DMBEDTLS_DEBUG=OFF -DPSA_API_TEST_SECURE_STORAGE=ON -DPSA_API_TEST_CRYPTO=OFF -DBL2=False -DBUILD_PLAT_TEST=False -DITS_CREATE_FLASH_LAYOUT=1 -DBUILD_DWARF_VERSION=2
make
